### ISSUE TITLE
Only define if not defined

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [VizuaaLOG/MicroLib-Utils#1]
Hi Thomas,

Are these methods only implemented if they are undefined or do they overwrite browser defined methods?

Perhaps it would be better to use polyfill
https://github.com/inexorabletash/polyfill/blob/master/polyfill.js#L4599

Thanks

**Comment by VizuaaLOG** [comment]
The methods are not assigned to any core object I.e. Array or object. These are mainly used in the Es6 source as an import statement and so are usually wrapped up by the build system you are using.

This way poly fills are not required in my opinion.
